### ISSUE TITLE
New Streamer card

### ISSUE THREAD

**Issue by caio-emidio** [brdevstreamers/brdevstreamers-ui#53]
I was thinking about it...
in my point of view, the card needs some improvements.

Actual Card:
![image](https://user-images.githubusercontent.com/5342402/159496359-1dd3901a-9732-4996-a04a-47a864be6d0d.png)

What i am thinking about:
![image](https://user-images.githubusercontent.com/5342402/159497485-616cecaf-0665-4022-b31e-f9509355961a.png)

If you want to change contribute: 

Figma File
https://www.figma.com/file/MOHsNERLK9l1fzNyezFHDK/Untitled?node-id=0%3A1

**Comment by lucasvsouza28** [comment]
woking on it.

**Comment by caio-emidio** [comment]
@lucasvsouza28 se possivel... acho que seria interessante ao carregar mover a tela levemente pra cima. Se vc ver o preview la no brstreamers.dev vc vai ver que a tela fica cortada pelo border radius ... Consegue dar uma olhada?

**Comment by lucasvsouza28** [comment]
Bom dia, agora que eu reparei, no figma tem o card com border-radius e sem, mas não tava claro que era pra tirar o border-radius no hover.
Você acha que fica melhor assim?

**Comment by lucasvsouza28** [comment]
> @lucasvsouza28 se possivel... acho que seria interessante ao carregar mover a tela levemente pra cima. Se vc ver o preview la no brstreamers.dev vc vai ver que a tela fica cortada pelo border radius ... Consegue dar uma olhada?

Fiz algumas alterações no PR #69.
